--Run the script on the secondary server

SELECT LS.PRIMARY_SERVER,LS.PRIMARY_DATABASE,LSD.RESTORE_DELAY,
DATEDIFF(MI,LMS.LAST_RESTORED_DATE,GETDATE()) AS TIME_SINCE_LAST_RESTORE,
LMS.LAST_COPIED_DATE,LMS.LAST_RESTORED_DATE,LMS.LAST_COPIED_FILE,
LMS.LAST_RESTORED_FILE,
LSD.DISCONNECT_USERS,LS.BACKUP_SOURCE_DIRECTORY,
LS.BACKUP_DESTINATION_DIRECTORY,LS.MONITOR_SERVER
FROM MSDB.DBO.LOG_SHIPPING_SECONDARY LS
JOIN MSDB.DBO.LOG_SHIPPING_SECONDARY_DATABASES LSD
ON LSD.SECONDARY_ID=LS.SECONDARY_ID
JOIN MSDB.DBO.LOG_SHIPPING_MONITOR_SECONDARY LMS
ON LMS.SECONDARY_ID=LSD.SECONDARY_ID
